### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by BinWang28** [microsoft/promptbench#3]
Hello, I was running with this command. It is not finished after a couple of hours. Do you have an estimation of how long does it take?

```python main.py --model google/flan-t5-large --dataset mnli --attack textfooler --shot 0 --generate_len 20```

**Comment by Immortalise** [comment]
Hi there,

The estimated running time is difficult to predict due to the variability of the iterations per attack, which is highly dependent on the specifics of the prompts (the length of the prompt and the words used in the prompt). 

This command you're running iterates over 6 prompts, including 3 task-oriented and 3 role-oriented, please check the 'results/' directory to see if any prompts have completed.

**Comment by BinWang28** [comment]
Thanks, I see.

Understand that without batch processing, it will take quite some time.
