### ISSUE TITLE
prompt attack

### ISSUE THREAD

**Issue by zl-comment** [microsoft/promptbench#87]
eg
"Determine if the given pair of sentences displays entailment, neutral, or contradiction. Respond with 'entailment', 'neutral', or 'contradiction'\nQuestion: {content}\nAnswer:"
The prompt words Answer and Question cannot be modified. If they are attacked, the accuracy will drop a lot. I did not see this in the prompt words in your conclusion.

**Comment by kaijiezhu11** [comment]
Yes, in our setup, terms like ‘entailment’ and ‘Question’ are fixed and unmodifiable because we believe changing them is unnecessary and would cause a significant shift in meaning compared to the original clean prompts.

In this [example](https://github.com/microsoft/promptbench/blob/main/examples/prompt_attack.ipynb), you can define your own unmodifiable words.
