### ISSUE TITLE
MMLU subset

### ISSUE THREAD

**Issue by BinWang28** [microsoft/promptbench#9]
There are 800+ samples in the MMLU subset (data/mmlu.json). How does it work?

How does it aligns with 564 samples as introduced in paper?

**Comment by Immortalise** [comment]
Hi,

We stored the [MMLU validation dataset](https://huggingface.co/datasets/lukaemon/mmlu/viewer/philosophy/validation)  in JSON format. When loading the MMLU dataset, we select **10 samples from the validation set of each task**. However, not all tasks have 10 examples available in the validation set. Due to this, the total number of samples that are measured amounts to 564.

**Comment by BinWang28** [comment]
Thanks for the reply.

I mean there are around 870 samples in https://github.com/microsoft/promptbench/blob/main/data/MMLU.json.

Any hints on how it is constructed?

**Comment by Immortalise** [comment]
The JSON file has approximately 870 samples from 57 tasks' validation sets according to this [MMLU validation dataset](https://huggingface.co/datasets/lukaemon/mmlu/viewer/philosophy/validation).
